name: Deploy GitHub Pages

run-name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/configure-pages@v5

      - uses: subosito/flutter-action@v2

      - run: flutter pub get && flutter build web --base-href /riverpod_generics_sandbox/

      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

      - uses: actions/deploy-pages@v4
        id: deployment
